// <auto-generated />
using System;
using LegendaryOnline.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LegendaryOnline.Data.Migrations.Hero
{
    [DbContext(typeof(HeroDbContext))]
    partial class HeroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hero")
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LegendaryOnline.Data.Heroes.Hero", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Hero");

                    b.HasData(
                        new { ID = 1, Name = "Captain Ameria" }
                    );
                });

            modelBuilder.Entity("LegendaryOnline.Data.Heroes.HeroCard", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BaseAttack");

                    b.Property<int>("BaseRecruit");

                    b.Property<int>("Class");

                    b.Property<int>("Cost");

                    b.Property<int?>("HeroID");

                    b.Property<string>("ImagePath");

                    b.Property<string>("Name");

                    b.Property<int>("Team");

                    b.HasKey("ID");

                    b.HasIndex("HeroID");

                    b.ToTable("HeroCard");
                });

            modelBuilder.Entity("LegendaryOnline.Data.Heroes.HeroCard", b =>
                {
                    b.HasOne("LegendaryOnline.Data.Heroes.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroID");
                });
#pragma warning restore 612, 618
        }
    }
}
